- name: Install Angular on local machine
  hosts: localhost
  become: yes
  vars:
    nodejs_version: 16
  tasks:
    - name: Install Node.js
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - curl
        - gnupg2
      when: ansible_distribution == "Ubuntu"
    - name: Add Node.js PPA
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install Node.js and NPM
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - nodejs
        - npm
      when: ansible_distribution == "Ubuntu"
    - name: Install Angular CLI
      ansible.builtin.shell: npm install -g @angular/cli
