---
- name: Install and start Docker
  hosts: localhost
  become: true
  vars:
    docker_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
    docker_apt_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  tasks:
    - name: Add Docker APT key
      apt_key:
        url: "{{ docker_apt_key_url }}"
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "{{ docker_apt_repo }}"
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Check if Docker is running
      shell: docker ps
      register: docker_running
      ignore_errors: yes

    - name: Start Docker if not running
      service:
        name: docker
        state: started
      when: docker_running.rc != 0


