---
- name: Install and start Docker and Docker Compose
  hosts: localhost
  become: true
  vars:
    docker_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
    docker_apt_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    docker_compose_url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
    docker_compose_path: /usr/local/bin/docker-compose
  tasks:
    - name: Add Docker APT key
      apt_key:
        url: "{{ docker_apt_key_url }}"
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "{{ docker_apt_repo }}"
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Check if Docker is running
      shell: docker ps
      register: docker_running
      ignore_errors: yes

    - name: Start Docker if not running
      service:
        name: docker
        state: started
      when: docker_running.rc != 0

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      when: ansible_user != "root"

    - name: Install Docker Compose
      get_url:
        url: "{{ docker_compose_url }}"
        dest: "{{ docker_compose_path }}"
        mode: 'u+x'

    - name: Set executable permissions for current user
      file:
        path: "{{ docker_compose_path }}"
        mode: "0755"
      when: ansible_user != "root"

    - name: Verify Docker Compose installation
      shell: docker-compose --version
      register: docker_compose_version
      failed_when: docker_compose_version.rc != 0
